# Generated by Django 4.2 on 2024-09-15 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, default='Не указано', max_length=50, null=True, verbose_name='страна'),
        ),
        migrations.AlterField(
            model_name='user',
            name='num_phone',
            field=models.CharField(blank=True, default='Не указано', max_length=35, null=True, verbose_name='телефон'),
        ),
    ]
